### ISSUE TITLE
Button - a tag not resizing

### ISSUE THREAD

**Issue by char1129** [char1129/svg-icon-sets#2]
As per our convo in class.
The a tag appears to be immune to any resizing attempts. @hellachella @jessjodoin

Thank you!

**Comment by hellachella** [comment]
Checking it out!

**Comment by JessJodoin** [comment]
This might be silly (or not work) but what if you tried targeting `a` as opposed to `div a` in main.css?

**Comment by hellachella** [comment]
The CSS in .btn is overriding it. Remove `font: inherit;`

**Comment by JessJodoin** [comment]
Oh yup

**Comment by char1129** [comment]
**Thank you!**
