### ISSUE TITLE
Invasion of the whitespace.

### ISSUE THREAD

**Issue by char1129** [char1129/svg-icon-sets#3]
When I have an issue - it turns out to be many. (The one assignment that seems to keep tripping me up out of the whole semester...)

Thank you for the help, really!
@hellaChella

**Comment by hellachella** [comment]
Put display grid in the section as well. Literally the only thing that should be in the `body` tag is `margin: 0;`

**Comment by hellachella** [comment]
It might be a good idea to set up `grid-areas` as well in`section`.

**Comment by char1129** [comment]
I'll give that a shot and let you know! Thank you!

**Comment by char1129** [comment]
@hellachella I've implemented the grids and and I'm starting to move onto the other query sizes because....
The whitespace is still there... :( 

![tenor](https://user-images.githubusercontent.com/55107755/96290364-76682a00-0fb4-11eb-96f2-8868a44bb178.gif)

**Comment by hellachella** [comment]
commit and I'll see where you are

**Comment by char1129** [comment]
@hellachella done and done.

**Comment by char1129** [comment]
I'm working on main2.css as well - I should of pointed that out but you may of noticed 😊   - Which is now made into the main.css. I removed the duplicate file.

**Comment by char1129** [comment]
@hellachella Tried adding overflow-x and overflow-y: hidden to both the html and body - didn't work.
It's the only thing holding me up from handing this assignment now...

**Comment by char1129** [comment]
@hellachella Figured it out finally after guessing it had something to do with the HTML css and muted the whole section to find the white space gone.
It was height: 100%; in the html tag that was the issue. 
Corrected, committed and submitted!
